project_id = "ifftfzcyxkkduxnexdwm"

[functions.send-email]
verify_jwt = false

[functions.payment-notify]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.delete-member]
verify_jwt = false