// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifftfzcyxkkduxnexdwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZnRmemN5eGtrZHV4bmV4ZHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwODIzMzAsImV4cCI6MjA3NzY1ODMzMH0.WpJCyOyD6ffzVn_ApZEFNPK1ZSxK3DTTeUfxPn1loJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});